#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="GIT"
export ZOPEN_CONFIGURE="./Configure"

if [ "${ZOPEN_INSTALL_DIR}x" = "x" ]; then
  export ZOPEN_INSTALL_DIR="${HOME}/zopen/prod/${dir}"
fi
export ZOPEN_CONFIGURE_OPTS="-Dprefix=${ZOPEN_INSTALL_DIR} -Duserelocatableinc -Dusedevel -des -Duse64bitall -Dusedl"
export ZOPEN_CHECK_OPTS="test"
export ZOPEN_GIT_URL="https://github.com/Perl/perl5.git"
export ZOPEN_GIT_DEPS="git make"
export ZOPEN_GIT_BRANCH="blead"

# Perl Environment variables
export INSTALLFLAGS="+v"

zopen_append_to_env() {
cat <<EOF
for libperl in \$(find \${PWD}/ -name "libperl.so"); do
  libperl=\$(dirname "\${libperl}")
  export LIBPATH="\${libperl}:\$LIBPATH"
done
if ls \${mydir}/lib/perl[0-9]* >/dev/null 2>&1; then
  PERL5LIB_ROOT=\$( cd \${PWD}/lib/perl[0-9]/[0-9]*; echo \$PWD )
else
  PERL5LIB_ROOT=\$( cd \${PWD}/lib/[0-9]*; echo \$PWD )
fi
export PERL5LIB="\${PERL5LIB_ROOT}:\${PERL5LIB_ROOT}/os390"
EOF
}

zopen_check_results()
{
#!/bin/sh
# perl should have less than 22 failurs
# Determine number of failures by looking at "Failed.*tests out of" line
#
chk="$2_check.log"

set -x
failures=$(grep "Failed.*tests out of" ${chk} | cut -f2 -d' ')
if [ ${failures} -gt 21 ]; then
  exit 2
else
  exit 1
fi
}

